### PR TITLE
Add sleeping cat with computer

### PR DESCRIPTION
**Pull request by daniellecrobinson**
also some .ai files for easier editing

### CODE REVIEW

**Comment by paulcpederson** [comment]
@daniellecrobinson is this meant to be opened against donut-js? Looks like you are making a new site. 

Or maybe I'm just confused 😭

**Comment by matthewmcvickar** [comment]
@maxogden This was a fork made for a separate site for a hack day, right? Should we close this?

**Comment by daniellecrobinson** [comment]
Yes, sorry about this! I am new to github to tbh am not sure how this wound up in the Donuts zone.

**Comment by paulcpederson** [comment]
no worries, cool cat drawings 🙌

**Pull request closed without merging**
