### PR TITLE
Added embedded videos to speaker page

### PR DESCRIPTION
**Pull request by jwithington**
This is for https://github.com/donut-js/donut-js.github.io/issues/44

I haven't made the videos responsive yet, but I figured done was better than perfect. 

Woo! 🍩

### CODE REVIEW

**Comment by paulcpederson** [comment]
@jwithington :+1: 

Usually I do responsive videos by adding a wrap that uses padding to preserve aspect ratio. So:

```
.video-wrap {
  position: relative;
  padding-bottom: 56.25%;
  height: 0;
  overflow: hidden;
}

.video-wrap iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
 }
```

```
<div class="video-wrap">
  <!-- no width and height, let container determine scale -->
  <iframe src="https://www.youtube.com/embed/w5cQiDflGNc" frameborder="0" allowfullscreen</iframe>
</div>
```

Not sure if something like that would work here.

**Comment by jwithington** [comment]
Thanks @paulcpederson !  I haven't had a chance to work on it yet, but that'll help!

**Comment by jwithington** [comment]
Awesome -- seems to be lookin' all good and responsive and such now, after incorporating @paulcpederson 's suggestion. Hope it's ready to go for y'all!

**Comment by matthewmcvickar** [comment]
@jwithington Thank you so much for doing this! I've merged in your changes and pushed it to the production website.

**Comment by paulcpederson** [comment]
🎉

**Pull request merged**
