### PR TITLE
Add slack link to main site

### PR DESCRIPTION
**Pull request by jwithington**
Completes, in a very small way, https://github.com/donut-js/donut-js.github.io/issues/52

I make it look as close as possible to what y'all already had, without also making it look odd. 🍩

### CODE REVIEW

**Comment by matthewmcvickar** [comment]
Thank you so much! I made a little adjustment. Merging now!

**Comment by jwithington** [comment]
Hahaha yeah I was erring on the side of "make it look like the other links". 🍩

**Comment by matthewmcvickar** [comment]
Yeah, you did it right! I’m changing it closer to what you did. Apologies; I’m indecisive and twitchy from coffee. 🙃
image

**Comment by jwithington** [comment]
Hahaha no worries!  I like that even better. 😄

**Pull request merged**
